send_ebook_to_device:
  fields:
    item_id:
      required: true
      selector:
        text:
    device_name:
      required: false
      selector:
        text:
    force:
      required: false
      default: false
      selector:
        boolean:
send_item:
  fields:
    item_id:
      required: true
      selector:
        text:
    device_name:
      required: false
      selector:
        text:
    force:
      required: false
      default: false
      selector:
        boolean:
reset_sent_item:
  fields:
    item_id:
      required: true
      selector:
        text:
    device_name:
      required: false
      selector:
        text:
